

from PyQt5 import QtCore, QtGui, QtWidgets


class LogIn(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 452)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(3000, 1000))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Parent = QtWidgets.QGroupBox(self.centralwidget)
        self.Parent.setStyleSheet("QWidget #Parent{\n"
"background-color:rgb(223, 223, 223);\n"
"    border-radius: 10px; /* Set border radius for rounded corners */\n"
"\n"
"    background-repeat: no-repeat;\n"
"background-position: center;"
"    background-size: contain; /* Scale the background image to fit */\n"
"    background-image: url(images//login-image.jpeg);\n"
"}")
        self.Parent.setObjectName("Parent")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Parent)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(267, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(self.Parent)
        self.groupBox.setStyleSheet("background-color:Transparent;\n"
"border:none;")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.signupbox = QtWidgets.QGroupBox(self.groupBox)
        self.signupbox.setObjectName("signupbox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.signupbox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(63, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.signupbox)
        self.label_2.setMaximumSize(QtCore.QSize(212, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:black;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.signupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(69, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(63, 71, 105);\n"
" background-color: transparent;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(102, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addWidget(self.signupbox, 4, 0, 1, 1)
        self.passwordbox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.passwordbox_2.setObjectName("passwordbox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.passwordbox_2)
        self.horizontalLayout_6.setContentsMargins(-1, 1, -1, 13)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.passwordbox = QtWidgets.QGroupBox(self.passwordbox_2)
        self.passwordbox.setStyleSheet("")
        self.passwordbox.setObjectName("passwordbox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.passwordbox)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 12)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.passwordbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(63, 71, 105);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.textEdit_2 = QtWidgets.QTextEdit(self.passwordbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 28))
        self.textEdit_2.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border: 2px solid  rgb(230, 230, 230); /* Set border width and color */\n"
"    border-radius: 10px; /* Set border radius for rounded corners */")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_4.addWidget(self.textEdit_2)
        self.horizontalLayout_6.addWidget(self.passwordbox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 9, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.gridLayout.addWidget(self.passwordbox_2, 2, 0, 1, 1)
        self.loginbox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.loginbox_2.setObjectName("loginbox_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.loginbox_2)
        self.horizontalLayout_8.setContentsMargins(-1, 44, -1, 28)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.label = QtWidgets.QLabel(self.loginbox_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(63, 71, 105);\n"
" background-color: transparent;\n"
"border: none;\n"
"border-radius: 10px; /* Set border radius for rounded corners */\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.gridLayout.addWidget(self.loginbox_2, 0, 0, 1, 1)
        self.usernamebox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.usernamebox_2.setObjectName("usernamebox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.usernamebox_2)
        self.horizontalLayout_4.setContentsMargins(-1, 12, -1, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.usernamebox = QtWidgets.QGroupBox(self.usernamebox_2)
        self.usernamebox.setStyleSheet("")
        self.usernamebox.setObjectName("usernamebox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.usernamebox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.usernamebox)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(63, 71, 105);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.textEdit_3 = QtWidgets.QTextEdit(self.usernamebox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_3.sizePolicy().hasHeightForWidth())
        self.textEdit_3.setSizePolicy(sizePolicy)
        self.textEdit_3.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_3.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border: 2px solid  rgb(230, 230, 230); /* Set border width and color */\n"
"    border-radius: 10px; /* Set border radius for rounded corners */")
        self.textEdit_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout.addWidget(self.textEdit_3)
        self.horizontalLayout_4.addWidget(self.usernamebox)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.gridLayout.addWidget(self.usernamebox_2, 1, 0, 1, 1)
        self.loginbox = QtWidgets.QGroupBox(self.groupBox)
        self.loginbox.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"\n"
"")
        self.loginbox.setObjectName("loginbox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.loginbox)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.Login_button = QtWidgets.QPushButton(self.loginbox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Login_button.setFont(font)
        self.Login_button.setAutoFillBackground(False)
        self.Login_button.setStyleSheet("color: rgb(63, 71, 105);\n"
" background-color: transparent;\n"
"border: 2px solid rgb(63, 71, 105);\n"
"border-radius: 10px; /* Set border radius for rounded corners */\n"
"")
        self.Login_button.setObjectName("Login_button")
        self.horizontalLayout_2.addWidget(self.Login_button)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.gridLayout.addWidget(self.loginbox, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.Parent, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Don\'t Have An Account?"))
        self.pushButton.setText(_translate("MainWindow", "SignUp"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "Enter Password"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.label_3.setText(_translate("MainWindow", "UserName"))
        self.textEdit_3.setPlaceholderText(_translate("MainWindow", "Enter UserName"))
        self.Login_button.setText(_translate("MainWindow", "  Login  "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = LogIn()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
