import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 816)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #1e1e2f;\n"
"border:none;\n"
"color:#ffffff;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.title = QtWidgets.QHBoxLayout()
        self.title.setObjectName("title")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.title.addItem(spacerItem)
        self.Title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        self.Title.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setStyleSheet("border:none;")
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.title.addWidget(self.Title)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.title.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.title)
        self.extensionBox = QtWidgets.QGroupBox(self.centralwidget)
        self.extensionBox.setObjectName("extensionBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.extensionBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.flexion_deg = QtWidgets.QLCDNumber(self.extensionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flexion_deg.sizePolicy().hasHeightForWidth())
        self.flexion_deg.setSizePolicy(sizePolicy)
        self.flexion_deg.setMaximumSize(QtCore.QSize(16777215, 40))
        self.flexion_deg.setStyleSheet("border: 1.2px solid #ffffff;\n"
"border-style: outset;\n"
"border-radius: 15px;")
        self.flexion_deg.setObjectName("flexion_deg")
        self.horizontalLayout_2.addWidget(self.flexion_deg)
        self.flex_deg_label = QtWidgets.QLabel(self.extensionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flex_deg_label.sizePolicy().hasHeightForWidth())
        self.flex_deg_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.flex_deg_label.setFont(font)
        self.flex_deg_label.setObjectName("flex_deg_label")
        self.horizontalLayout_2.addWidget(self.flex_deg_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.flexion_per = QtWidgets.QLCDNumber(self.extensionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flexion_per.sizePolicy().hasHeightForWidth())
        self.flexion_per.setSizePolicy(sizePolicy)
        self.flexion_per.setMaximumSize(QtCore.QSize(16777215, 40))
        self.flexion_per.setStyleSheet("border: 1.2px solid #ffffff;\n"
"border-style: outset;\n"
"border-radius: 15px;")
        self.flexion_per.setObjectName("flexion_per")
        self.horizontalLayout_3.addWidget(self.flexion_per)
        self.flex_per_label = QtWidgets.QLabel(self.extensionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flex_per_label.sizePolicy().hasHeightForWidth())
        self.flex_per_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.flex_per_label.setFont(font)
        self.flex_per_label.setObjectName("flex_per_label")
        self.horizontalLayout_3.addWidget(self.flex_per_label)
        spacerItem2 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.flexion = QtWidgets.QGraphicsView(self.extensionBox)
        self.flexion.setStyleSheet("border: 1.2px solid #ffffff;\n"
"border-style: outset;\n"
"border-radius: 15px;")
        self.flexion.setObjectName("flexion")
        self.gridLayout_3.addWidget(self.flexion, 0, 1, 2, 1)
        self.label_3 = QtWidgets.QLabel(self.extensionBox)
        self.label_3.setStyleSheet("border: 1.2px solid #ffffff;\n"
"border-style: outset;\n"
"border-radius: 15px;\n"
"font: 75 10pt \"MS Shell Dlg 2\" ;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.extensionBox)
        self.abductionBox = QtWidgets.QGroupBox(self.centralwidget)
        self.abductionBox.setObjectName("abductionBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.abductionBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.adduction_deg = QtWidgets.QLCDNumber(self.abductionBox)
        self.adduction_deg.setMaximumSize(QtCore.QSize(16777215, 40))
        self.adduction_deg.setStyleSheet("border: 1.2px solid #ffffff;\n"
"border-style: outset;\n"
"border-radius: 15px;")
        self.adduction_deg.setObjectName("adduction_deg")
        self.horizontalLayout_4.addWidget(self.adduction_deg)
        self.add_deg_label = QtWidgets.QLabel(self.abductionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_deg_label.sizePolicy().hasHeightForWidth())
        self.add_deg_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_deg_label.setFont(font)
        self.add_deg_label.setObjectName("add_deg_label")
        self.horizontalLayout_4.addWidget(self.add_deg_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.adduction_per = QtWidgets.QLCDNumber(self.abductionBox)
        self.adduction_per.setMaximumSize(QtCore.QSize(16777215, 40))
        self.adduction_per.setStyleSheet("border: 1.2px solid #ffffff;\n"
"border-style: outset;\n"
"border-radius: 15px;")
        self.adduction_per.setObjectName("adduction_per")
        self.horizontalLayout_5.addWidget(self.adduction_per)
        self.add_per_label = QtWidgets.QLabel(self.abductionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_per_label.sizePolicy().hasHeightForWidth())
        self.add_per_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_per_label.setFont(font)
        self.add_per_label.setObjectName("add_per_label")
        self.horizontalLayout_5.addWidget(self.add_per_label)
        spacerItem3 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.adduction = QtWidgets.QGraphicsView(self.abductionBox)
        self.adduction.setStyleSheet("border: 1.2px solid #ffffff;\n"
"border-style: outset;\n"
"border-radius: 15px;")
        self.adduction.setObjectName("adduction")
        self.gridLayout_2.addWidget(self.adduction, 0, 1, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.abductionBox)
        self.label_2.setStyleSheet("border: 1.2px solid #ffffff;\n"
"border-style: outset;\n"
"border-radius: 15px;\n"
"font: 75 10pt \"MS Shell Dlg 2\" ;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.abductionBox)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.extension_deg = QtWidgets.QLCDNumber(self.groupBox)
        self.extension_deg.setMaximumSize(QtCore.QSize(16777215, 40))
        self.extension_deg.setStyleSheet("border: 1.2px solid #ffffff;\n"
"border-style: outset;\n"
"border-radius: 15px;")
        self.extension_deg.setObjectName("extension_deg")
        self.horizontalLayout_6.addWidget(self.extension_deg)
        self.ext_deg_label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ext_deg_label.sizePolicy().hasHeightForWidth())
        self.ext_deg_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ext_deg_label.setFont(font)
        self.ext_deg_label.setObjectName("ext_deg_label")
        self.horizontalLayout_6.addWidget(self.ext_deg_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.extension_per = QtWidgets.QLCDNumber(self.groupBox)
        self.extension_per.setMaximumSize(QtCore.QSize(16777215, 40))
        self.extension_per.setStyleSheet("border: 1.2px solid #ffffff;\n"
"border-style: outset;\n"
"border-radius: 15px;")
        self.extension_per.setObjectName("extension_per")
        self.horizontalLayout_7.addWidget(self.extension_per)
        self.ext_per_label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ext_per_label.sizePolicy().hasHeightForWidth())
        self.ext_per_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ext_per_label.setFont(font)
        self.ext_per_label.setObjectName("ext_per_label")
        self.horizontalLayout_7.addWidget(self.ext_per_label)
        spacerItem4 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.extension = QtWidgets.QGraphicsView(self.groupBox)
        self.extension.setStyleSheet("border: 1.2px solid #ffffff;\n"
"border-style: outset;\n"
"border-radius: 15px;")
        self.extension.setObjectName("extension")
        self.gridLayout.addWidget(self.extension, 0, 1, 2, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setStyleSheet("border: 1.2px solid #ffffff;\n"
"border-style: outset;\n"
"border-radius: 15px;\n"
"font: 75 10pt \"MS Shell Dlg 2\" ;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(738, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border: 1.2px solid #ffffff;\n"
"border-style: outset;\n"
"border-radius: 15px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Shoulder Mobility Assesement"))
        self.flex_deg_label.setText(_translate("MainWindow", "Degrees"))
        self.flex_per_label.setText(_translate("MainWindow", "%"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.add_deg_label.setText(_translate("MainWindow", "Degrees"))
        self.add_per_label.setText(_translate("MainWindow", "%"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.ext_deg_label.setText(_translate("MainWindow", "Degrees"))
        self.ext_per_label.setText(_translate("MainWindow", "%"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "Return"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
